name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
jobs:
  cloudrunProd:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: |-
          docker build -t gcr.io/dotted-cedar-350702/meli-challenge-api -t latest .
      
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.SERVICE_ACCOUNT_KEYS }}

      - name: Push to Container Registry
        run: |-
          docker push gcr.io/dotted-cedar-350702/meli-challenge-api

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: meli-challenge-api
          image: gcr.io/dotted-cedar-350702/meli-challenge-api
          project_id: dotted-cedar-350702 
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEYS }}
